version: '3.8'

services:
  # Service API Flask
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watermark-api
    restart: unless-stopped
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1

networks:
  default:
    name: watermark-network